name: deskmate_display
description: DESKMATE Raspberry Pi 5 Atlas status display.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  dbus: ^0.7.12
  audioplayers_atlas:
    path: /opt/flutter-atlas-plugins/packages/flutter-plugin-atlas-audioplayers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/deskmate_test_music.mp3
